wip

diff --git a/.github/workflows/front-end-tests.yml b/.github/workflows/front-end-tests.yml
--- a/.github/workflows/front-end-tests.yml
+++ b/.github/workflows/front-end-tests.yml
@@ -23,7 +23,15 @@ jobs:
           npm install
 
       - name: Run Angular Tests with Code Coverage
-        run: cd ${{ github.workspace }}/front && npm run test:prod
+        run: |
+          cd ${{ github.workspace }}/front
+          npm run test:prod
+
+      - name: List Coverage Files
+        run: |
+          cd ${{ github.workspace }}/front/coverage/bobapp
+          ls -la
+          cat lcov.info || echo "lcov.info not found"
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v4
@@ -31,25 +39,12 @@ jobs:
           name: test-results
           path: ${{ github.workspace }}/front/coverage/bobapp
 
-      - name: Upload LCOV Report
-        uses: actions/upload-artifact@v4
-        with:
-          name: lcov-report
-          path: ${{ github.workspace }}/front/coverage/bobapp/lcov.info
-
   sonar_front:
     needs: [test_front]
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Download LCOV Report
-        uses: actions/download-artifact@v4
-        with:
-          name: lcov-report
-          path: ${{ github.workspace }}/front/coverage/bobapp
+      - uses: actions/checkout@v4
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
@@ -59,7 +54,7 @@ jobs:
           args: >
             -Dsonar.organization=shiffff
             -Dsonar.projectKey=shiffff-bobapp-front
-            -Dsonar.typescript.lcov.reportPaths=front/coverage/bobapp/lcov.info
+            -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
@@ -67,7 +62,6 @@ jobs:
   docker_create_push_front:
     needs: [test_front, sonar_front]
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v4
 
